name = "ParameterizedNotebooks"
uuid = "efe69fdf-5f6b-4971-99df-296990405262"
authors = ["Marius Millea <mariusmillea@gmail.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "0.5"
julia = "1.0"
